import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CodeTranslator from '../components/CodeTranslator';

const Home: NextPage = () => {

  return (
    <div className={styles.CodeMirror}>
      <Head>
        <title>Code Explainer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chatgpt-icon.svg" />
      </Head>

      <div>
        <div className={styles.headerCard}>
          <h1>Code Explainer</h1>
          <p style={{ 'fontSize': '24px' }}>
            Understand snippets of code in javascript, python and java by asking <b>chatgpt</b> to explain them in one of the top 10 most spoken languages in the world.
          </p>
        </div>
        <CodeTranslator />
      </div>
    </div>
  )
}

export default Home
